syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.bruno.grpc";
option java_outer_classname = "AdvinharProto";

import "google/protobuf/empty.proto";

service Controller {

  // Inicia o jogo
  rpc iniciarJogo(google.protobuf.Empty) returns (DicaReply);

  // Sorteia número para cliente
  rpc entrar(JogadorRequest) returns (JogadorReply);

  // Obtem estado do jogador
  rpc obterEstado(google.protobuf.Empty) returns (EstadoReply);

  // Envia dica
  rpc enviarDica(DicaRequest) returns (DicaReply);

  rpc receberDicas(JogadorRequest) returns (stream DicaReply);

  // Tentativa de adivinhar
  rpc adivinharNumero(AdivinharRequest) returns (AdivinharReply);

  // Chat em tempo real entre jogadores
  rpc enviarMensagemChat(ChatRequest) returns (ChatReply);
  rpc receberMensagensChat(JogadorRequest) returns (stream ChatReply);
}

enum EstadoJogo {
  ESPERANDO_INICIAR_JOGO = 0;
  ESPERANDO_DICA = 1;
  ESPERANDO_ADVINHAR = 2;
}

message JogadorRequest {
  string nick = 1;
}

message JogadorReply {
  bool sucesso = 1;
  string message = 2;
  string objeto = 3;
}

message EstadoReply {
  string jogadorAtual = 1;
  string jogadorInicial = 2;
  int32 rodada = 3;
  EstadoJogo estado = 4;
  string dicaAtual = 5;
  string autorDicaAtual = 6;
}

message DicaRequest {
  string autor = 1;
  string dica = 2;
}

message DicaReply {
  string message = 1;
}

message AdivinharRequest {
  string jogador = 1;
  string alvo = 2;
  string objeto = 3;
}

message AdivinharReply {
  bool acertou = 1;
  string message = 2;
}

message ChatRequest {
  string nick = 1;
  string texto = 2;
  string horario = 3;
}

message ChatReply {
  string nick = 1;
  string texto = 2;
  string horario = 3;
}
